"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var dotenv_1 = require("dotenv");
var cors_1 = require("cors");
var cors_2 = require("./config/cors");
var morgan_1 = require("morgan");
var db_ts_1 = require("./config/db.ts");
var authRoutes_ts_1 = require("./routes/authRoutes.ts");
var projectRoutes_ts_1 = require("./routes/projectRoutes.ts");
dotenv_1.default.config();
(0, db_ts_1.connectDB)();
var app = (0, express_1.default)();
app.use((0, cors_1.default)(cors_2.corsConfig));
app.use((0, morgan_1.default)('dev'));
app.use(express_1.default.json());
app.use('/api/auth', authRoutes_ts_1.default);
app.use('/api/projects', projectRoutes_ts_1.default);
exports.default = app;
